name: CI

on:
  push:
    branches:
      - master
    paths:
      - 'tests/**'
      - 'nflows/**'
      - '.github/workflows/**'
      - 'setup.py'
      - 'environment.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'tests/**'
      - 'nflows/**'
      - '.github/workflows/**'
      - 'setup.py'
      - 'environment.yml'

jobs:
  test:
	name: Python ${{ matrix.python-version }} - ${{ matrix.os }} - ${{ github.event_name }} 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.7']
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    
    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install package"
        run: |
            python -m pip install --upgrade pip
            python setup.py install
      - name: "Run tests"
        run: python -m unittest discover
